### ISSUE TITLE
Housing Price Prediction

### ISSUE THREAD

**Issue by perireddyvaka** [KIET-NEST-PROJECTS-KBH/E-2F-217#1]
Analyze housing data to predict the selling prices of houses based on 
features like square footage, number of bedrooms, etc.

**Comment by benayaram** [comment]
Today We assigned work to the team members 
frontend for two members and Backend for 4 members

**Comment by perireddyvaka** [comment]
Okay make it complete by 27th September

**Comment by benayaram** [comment]
Today We Worked on Project With basic frontend and Project is Working and Getting Predicted Price 
We want to Continue the Frontend More attractively and Modify the backend

![image](https://github.com/KIET-NEST-PROJECTS-KBH/E-2F-217/assets/96018533/6f274c70-402a-455f-974e-0d5665868ba5)

**Comment by perireddyvaka** [comment]
Great!

**Comment by benayaram** [comment]
Thank you

**Comment by yerramnaiduparupalli** [comment]
now we are working on frontend to make frontend attractively.

**Comment by benayaram** [comment]
Frontend Is completed

**Comment by benayaram** [comment]
I Uploaded the Files in my Branch and Our team members Developing remaining work Taking dataset and get data

Backend Also Completed But It is Taken from the Sample Data Like This

# Example data for training the model
X = np.array([
    [1500, 2, 'location1'],
    [1800, 3, 'location2'],
    [1200, 2, 'location1'],
    [2200, 4, 'location3'],
    [1700, 3, 'location2']
])
y = [250000, 320000, 190000, 410000, 295000]

**Comment by perireddyvaka** [comment]
Thanks, I'll check them out.

**Comment by benayaram** [comment]
Today our team complete project with that remaining code

**Comment by benayaram** [comment]
![image](https://github.com/KIET-NEST-PROJECTS-KBH/E-2F-217/assets/96018533/51ba2431-5d9f-4a25-89bc-22a84aa1bdb3)
Project Completed

**Comment by perireddyvaka** [comment]
Looks great!
